from ListOfDirectoriesForAsunaAi import __FOLDER_PATH__
from ListOfDirectoriesForAsunaAi_2 import __PROGRAM_NAME__
from Pokemonarrayscript import *
from MasterScriptForte_Redone_2 import *
import pandas as pd
df = pd.read_excel (r'C:\ASUNAAI\EXTENSIONS\XLSX\TESTDATAFORPYTHONSCRIPT.xlsx', sheet_name='POKEMON000DATA')
a = df['POKEMON_NAME_LLR']
b = df['LOWERLEVELRANGE']
c = df['HIGHERLEVELRANGE']
d = df['ENCOUNTERPERCENTAGE']
e = df['TIME_OF_DAY']
f = df['SEASON_DATA']
g = df['ROUTE_NAME']
h = df['HABITAT_DEX_DATA']
print(PIDGEY,CAN,BE,FOUND,WITH,LEVELS,BETWEEN,LEVEL,df.LOWERLEVELRANGE[0],TO,LEVEL,df.HIGHERLEVELRANGE[0])
print("Pokemon That Show Up At Day")
print (ROUTE,df.ROUTE_NAME[0],HAS,A,df.ENCOUNTERPERCENTAGE[1],CHANCE,TO,FIND,WURMPLE,INSIDE,df.HABITAT_DEX_DATA[0],DURING,df.TIME_OF_DAY[0])
print (ROUTE,df.ROUTE_NAME[0],HAS,A,df.ENCOUNTERPERCENTAGE[0],CHANCE,TO,FIND,PACHIRISU,INSIDE,df.HABITAT_DEX_DATA[0],DURING,df.TIME_OF_DAY[0])
print (ROUTE,df.ROUTE_NAME[0],HAS,A,df.ENCOUNTERPERCENTAGE[1],CHANCE,TO,FIND,SENTRET,INSIDE,df.HABITAT_DEX_DATA[0],DURING,df.TIME_OF_DAY[0])
print("******************************************************************")
print("Pokemon That Show Up At Night")
print (ROUTE,df.ROUTE_NAME[0],HAS,A,df.ENCOUNTERPERCENTAGE[1],CHANCE,TO,FIND,WURMPLE,INSIDE,df.HABITAT_DEX_DATA[0],DURING,df.TIME_OF_DAY[1])
print (ROUTE,df.ROUTE_NAME[0],HAS,A,df.ENCOUNTERPERCENTAGE[0],CHANCE,TO,FIND,PIKACHU,INSIDE,df.HABITAT_DEX_DATA[0],DURING,df.TIME_OF_DAY[1])
print (ROUTE,df.ROUTE_NAME[0],HAS,A,df.ENCOUNTERPERCENTAGE[1],CHANCE,TO,FIND,SPINARAK,INSIDE,df.HABITAT_DEX_DATA[0],DURING,df.TIME_OF_DAY[1])





