from Language_Early_Stage import *
IF,DATA,GIVEN,A,CATEGORY,DOES,NOT,MATCH,DATA,WITH,CATEGORY
    THEN,SCAN,OTHER,CATEGORIES,EXISTING,AND,CALCULATE,CATEGORY,WITH,SIMILAR,MATCH,TO,DATA,WITHIN,CATEGORY
END,IF,STATEMENT