from ListOfDirectoriesForAsunaAi import __FOLDER_PATH__
from ListOfDirectoriesForAsunaAi_2 import __PROGRAM_NAME__
from Pokemonarrayscript import *
from MasterScriptForte_Redone_2 import *
import pandas as pd
df = pd.read_excel (r'C:\ASUNAAI\EXTENSIONS\XLSX\TESTDATAFORPYTHONSCRIPT2.xlsx', sheet_name='POKEMON000DATA')
a = df['POKEMON_LEVEL']

print(FLAAFFY,CAN,LEARN,THE,TECHNIQUE,THUNDERSHOCK,AT,LEVEL,df.POKEMON_LEVEL[9]) #Level 10
print(FLAAFFY,CAN,LEARN,THE,TECHNIQUE,CHARGE,AT,LEVEL,df.POKEMON_LEVEL[15]) #Level 16
print(FLAAFFY,CAN,LEARN,THE,TECHNIQUE,CHARGEBEAM,AT,LEVEL,df.POKEMON_LEVEL[17]) #Level 18 
print(FLAAFFY,CAN,LEARN,THE,TECHNIQUE,SHOCKWAVE,AT,LEVEL,df.POKEMON_LEVEL[22]) #Level 23
print(FLAAFFY,CAN,LEARN,THE,TECHNIQUE,ELECTRICTERRAIN,AT,LEVEL,df.POKEMON_LEVEL[25]) #Level 26
print(FLAAFFY,CAN,LEARN,THE,TECHNIQUE,SAFEGUARD,AT,LEVEL,df.POKEMON_LEVEL[37]) #Level 38
print(FLAAFFY,CAN,LEARN,THE,TECHNIQUE,SIGNALBEAM,AT,LEVEL,df.POKEMON_LEVEL[40]) #Level 41
print(FLAAFFY,CAN,LEARN,THE,TECHNIQUE,THUNDERBOLT,AT,LEVEL,df.POKEMON_LEVEL[47]) #Level 48
print(FLAAFFY,CAN,LEARN,THE,TECHNIQUE,CELEBRATE,AT,LEVEL,df.POKEMON_LEVEL[54]) #Level 59
print(FLAAFFY,CAN,LEARN,THE,TECHNIQUE,EARTHPOWER,AT,LEVEL,df.POKEMON_LEVEL[57]) #Level 58
print(FLAAFFY,CAN,LEARN,THE,TECHNIQUE,COTTONGUARD,AT,LEVEL,df.POKEMON_LEVEL[64]) #Level 65
print(FLAAFFY,CAN,LEARN,THE,TECHNIQUE,THUNDER,AT,LEVEL,df.POKEMON_LEVEL[72]) #Level 72