from ListOfDirectoriesForAsunaAi import __FOLDER_PATH__
from ListOfDirectoriesForAsunaAi_2 import __PROGRAM_NAME__
from Pokemonarrayscript import *
from MasterScriptForte_Redone_2 import *
import pandas as pd
df = pd.read_excel (r'C:\ASUNAAI\EXTENSIONS\XLSX\TESTDATAFORPYTHONSCRIPT2.xlsx', sheet_name='POKEMON000DATA')
a = df['POKEMON_LEVEL']

print(AMPHAROS,CAN,LEARN,THE,TECHNIQUE,THUNDERSHOCK,AT,LEVEL,df.POKEMON_LEVEL[14]) #Level 15
print(AMPHAROS,CAN,LEARN,THE,TECHNIQUE,CHARGE,AT,LEVEL,df.POKEMON_LEVEL[20]) #Level 21
print(AMPHAROS,CAN,LEARN,THE,TECHNIQUE,CHARGEBEAM,AT,LEVEL,df.POKEMON_LEVEL[22]) #Level 23 
print(AMPHAROS,CAN,LEARN,THE,TECHNIQUE,SHOCKWAVE,AT,LEVEL,df.POKEMON_LEVEL[27]) #Level 28
print(AMPHAROS,CAN,LEARN,THE,TECHNIQUE,ELECTRICTERRAIN,AT,LEVEL,df.POKEMON_LEVEL[30]) #Level 31
print(AMPHAROS,CAN,LEARN,THE,TECHNIQUE,SAFEGUARD,AT,LEVEL,df.POKEMON_LEVEL[42]) #Level 43
print(AMPHAROS,CAN,LEARN,THE,TECHNIQUE,SIGNALBEAM,AT,LEVEL,df.POKEMON_LEVEL[45]) #Level 46
print(AMPHAROS,CAN,LEARN,THE,TECHNIQUE,THUNDERBOLT,AT,LEVEL,df.POKEMON_LEVEL[52]) #Level 53
print(AMPHAROS,CAN,LEARN,THE,TECHNIQUE,CELEBRATE,AT,LEVEL,df.POKEMON_LEVEL[59]) #Level 60
print(AMPHAROS,CAN,LEARN,THE,TECHNIQUE,EARTHPOWER,AT,LEVEL,df.POKEMON_LEVEL[62]) #Level 63
print(AMPHAROS,CAN,LEARN,THE,TECHNIQUE,COTTONGUARD,AT,LEVEL,df.POKEMON_LEVEL[69]) #Level 70
print(AMPHAROS,CAN,LEARN,THE,TECHNIQUE,THUNDER,AT,LEVEL,df.POKEMON_LEVEL[77]) #Level 78