from ListOfDirectoriesForAsunaAi import __FOLDER_PATH__
from ListOfDirectoriesForAsunaAi_2 import __PROGRAM_NAME__
from Pokemonarrayscript import *
from MasterScriptForte_Redone_2 import *
import pandas as pd
df = pd.read_excel (r'C:\ASUNAAI\EXTENSIONS\XLSX\TESTDATAFORPYTHONSCRIPT2.xlsx', sheet_name='POKEMON000DATA')
a = df['POKEMON_LEVEL']

print(RATTATA,CAN,LEARN,THE,TECHNIQUE,TACKLE,AT,LEVEL,df.POKEMON_LEVEL[6]) #Level 7
print(RATTATA,CAN,LEARN,THE,TECHNIQUE,QUICKATTACK,AT,LEVEL,df.POKEMON_LEVEL[12]) #Level 13
print(RATTATA,CAN,LEARN,THE,TECHNIQUE,TAILSLAP,AT,LEVEL,df.POKEMON_LEVEL[16]) #Level 17 
print(RATTATA,CAN,LEARN,THE,TECHNIQUE,DOUBLEHIT,AT,LEVEL,df.POKEMON_LEVEL[19]) #Level 20
print(RATTATA,CAN,LEARN,THE,TECHNIQUE,TAKEDOWN,AT,LEVEL,df.POKEMON_LEVEL[24]) #Level 25
print(RATTATA,CAN,LEARN,THE,TECHNIQUE,SCREECH,AT,LEVEL,df.POKEMON_LEVEL[34]) #Level 33
print(RATTATA,CAN,LEARN,THE,TECHNIQUE,DOUBLETEAM,AT,LEVEL,df.POKEMON_LEVEL[37]) #Level 38
print(RATTATA,CAN,LEARN,THE,TECHNIQUE,HYPERFANG,AT,LEVEL,df.POKEMON_LEVEL[44]) #Level 45
print(RATTATA,CAN,LEARN,THE,TECHNIQUE,SUPERFANG,AT,LEVEL,df.POKEMON_LEVEL[51]) #Level 50
print(RATTATA,CAN,LEARN,THE,TECHNIQUE,ENDEAVOR,AT,LEVEL,df.POKEMON_LEVEL[54]) #Level 55
print(RATTATA,CAN,LEARN,THE,TECHNIQUE,FLAMEWHEEL,AT,LEVEL,df.POKEMON_LEVEL[61]) #Level 62
print(RATTATA,CAN,LEARN,THE,TECHNIQUE,PSYCHICFANGS,AT,LEVEL,df.POKEMON_LEVEL[68]) #Level 69