from ListOfDirectoriesForAsunaAi import __FOLDER_PATH__
from ListOfDirectoriesForAsunaAi_2 import __PROGRAM_NAME__
from Pokemonarrayscript import *
from MasterScriptForte_Redone_2 import *
import pandas as pd
df = pd.read_excel (r'C:\ASUNAAI\EXTENSIONS\XLSX\TESTDATAFORPYTHONSCRIPT2.xlsx', sheet_name='POKEMON000DATA')
a = df['POKEMON_LEVEL']

print(METANG,CAN,LEARN,THE,TECHNIQUE,TACKLE,AT,LEVEL,df.POKEMON_LEVEL[9]) #Level 10
print(METANG,CAN,LEARN,THE,TECHNIQUE,SAFEGUARD,AT,LEVEL,df.POKEMON_LEVEL[15]) #Level 16
print(METANG,CAN,LEARN,THE,TECHNIQUE,MAGNETBOMB,AT,LEVEL,df.POKEMON_LEVEL[17]) #Level 18 
print(METANG,CAN,LEARN,THE,TECHNIQUE,MAGNETRISE,AT,LEVEL,df.POKEMON_LEVEL[22]) #Level 23
print(METANG,CAN,LEARN,THE,TECHNIQUE,PSYCHICTERRAIN,AT,LEVEL,df.POKEMON_LEVEL[25]) #Level 26
print(METANG,CAN,LEARN,THE,TECHNIQUE,LOCKON,AT,LEVEL,df.POKEMON_LEVEL[37]) #Level 38
print(METANG,CAN,LEARN,THE,TECHNIQUE,REFRESH,AT,LEVEL,df.POKEMON_LEVEL[40]) #Level 41
print(METANG,CAN,LEARN,THE,TECHNIQUE,FOULPLAY,AT,LEVEL,df.POKEMON_LEVEL[47]) #Level 48
print(METANG,CAN,LEARN,THE,TECHNIQUE,SHADOWCLAW,AT,LEVEL,df.POKEMON_LEVEL[54]) #Level 59
print(METANG,CAN,LEARN,THE,TECHNIQUE,PSYCHOCUT,AT,LEVEL,df.POKEMON_LEVEL[57]) #Level 58
print(METANG,CAN,LEARN,THE,TECHNIQUE,METALCLAW,AT,LEVEL,df.POKEMON_LEVEL[64]) #Level 65
print(METANG,CAN,LEARN,THE,TECHNIQUE,IRONDEFENSE,AT,LEVEL,df.POKEMON_LEVEL[72]) #Level 72