from ListOfDirectoriesForAsunaAi import __FOLDER_PATH__
from ListOfDirectoriesForAsunaAi_2 import __PROGRAM_NAME__
from Pokemonarrayscript import *
from MasterScriptForte_Redone_2 import *
import pandas as pd
df = pd.read_excel (r'C:\ASUNAAI\EXTENSIONS\XLSX\TESTDATAFORPYTHONSCRIPT2.xlsx', sheet_name='POKEMON000DATA')
a = df['POKEMON_LEVEL']

print(MAREEP,CAN,LEARN,THE,TECHNIQUE,THUNDERSHOCK,AT,LEVEL,df.POKEMON_LEVEL[6]) #Level 7
print(MAREEP,CAN,LEARN,THE,TECHNIQUE,CHARGE,AT,LEVEL,df.POKEMON_LEVEL[12]) #Level 13
print(MAREEP,CAN,LEARN,THE,TECHNIQUE,CHARGEBEAM,AT,LEVEL,df.POKEMON_LEVEL[16]) #Level 17 
print(MAREEP,CAN,LEARN,THE,TECHNIQUE,SHOCKWAVE,AT,LEVEL,df.POKEMON_LEVEL[19]) #Level 20
print(MAREEP,CAN,LEARN,THE,TECHNIQUE,ELECTRICTERRAIN,AT,LEVEL,df.POKEMON_LEVEL[24]) #Level 25
print(MAREEP,CAN,LEARN,THE,TECHNIQUE,SAFEGUARD,AT,LEVEL,df.POKEMON_LEVEL[34]) #Level 33
print(MAREEP,CAN,LEARN,THE,TECHNIQUE,SIGNALBEAM,AT,LEVEL,df.POKEMON_LEVEL[37]) #Level 38
print(MAREEP,CAN,LEARN,THE,TECHNIQUE,THUNDERBOLT,AT,LEVEL,df.POKEMON_LEVEL[44]) #Level 45
print(MAREEP,CAN,LEARN,THE,TECHNIQUE,CELEBRATE,AT,LEVEL,df.POKEMON_LEVEL[51]) #Level 50
print(MAREEP,CAN,LEARN,THE,TECHNIQUE,EARTHPOWER,AT,LEVEL,df.POKEMON_LEVEL[54]) #Level 55
print(MAREEP,CAN,LEARN,THE,TECHNIQUE,COTTONGUARD,AT,LEVEL,df.POKEMON_LEVEL[61]) #Level 62
print(MAREEP,CAN,LEARN,THE,TECHNIQUE,THUNDER,AT,LEVEL,df.POKEMON_LEVEL[68]) #Level 69