from ListOfDirectoriesForAsunaAi import __FOLDER_PATH__
from ListOfDirectoriesForAsunaAi_2 import __PROGRAM_NAME__
from Pokemonarrayscript import *
from MasterScriptForte_Redone_2 import *
import pandas as pd
df = pd.read_excel (r'C:\ASUNAAI\EXTENSIONS\XLSX\TESTDATAFORPYTHONSCRIPT2.xlsx', sheet_name='POKEMON000DATA')
a = df['POKEMON_LEVEL']

print(METAGROSS,CAN,LEARN,THE,TECHNIQUE,TACKLE,AT,LEVEL,df.POKEMON_LEVEL[14]) #Level 15
print(METAGROSS,CAN,LEARN,THE,TECHNIQUE,SAFEGUARD,AT,LEVEL,df.POKEMON_LEVEL[20]) #Level 21
print(METAGROSS,CAN,LEARN,THE,TECHNIQUE,MAGNETBOMB,AT,LEVEL,df.POKEMON_LEVEL[22]) #Level 23 
print(METAGROSS,CAN,LEARN,THE,TECHNIQUE,MAGNETRISE,AT,LEVEL,df.POKEMON_LEVEL[27]) #Level 28
print(METAGROSS,CAN,LEARN,THE,TECHNIQUE,PSYCHICTERRAIN,AT,LEVEL,df.POKEMON_LEVEL[30]) #Level 31
print(METAGROSS,CAN,LEARN,THE,TECHNIQUE,LOCKON,AT,LEVEL,df.POKEMON_LEVEL[42]) #Level 43
print(METAGROSS,CAN,LEARN,THE,TECHNIQUE,REFRESH,AT,LEVEL,df.POKEMON_LEVEL[45]) #Level 46
print(METAGROSS,CAN,LEARN,THE,TECHNIQUE,FOULPLAY,AT,LEVEL,df.POKEMON_LEVEL[52]) #Level 53
print(METAGROSS,CAN,LEARN,THE,TECHNIQUE,SHADOWCLAW,AT,LEVEL,df.POKEMON_LEVEL[59]) #Level 60
print(METAGROSS,CAN,LEARN,THE,TECHNIQUE,PSYCHOCUT,AT,LEVEL,df.POKEMON_LEVEL[62]) #Level 63
print(METAGROSS,CAN,LEARN,THE,TECHNIQUE,METALCLAW,AT,LEVEL,df.POKEMON_LEVEL[69]) #Level 70
print(METAGROSS,CAN,LEARN,THE,TECHNIQUE,IRONDEFENSE,AT,LEVEL,df.POKEMON_LEVEL[77]) #Level 78