from ListOfDirectoriesForAsunaAi import __FOLDER_PATH__
from ListOfDirectoriesForAsunaAi_2 import __PROGRAM_NAME__
from Pokemonarrayscript import *
from MasterScriptForte_Redone_2 import *
import pandas as pd
df = pd.read_excel (r'C:\ASUNAAI\EXTENSIONS\XLSX\TESTDATAFORPYTHONSCRIPT2.xlsx', sheet_name='POKEMON000DATA')
a = df['POKEMON_LEVEL']

print(BELDUM,CAN,LEARN,THE,TECHNIQUE,TACKLE,AT,LEVEL,df.POKEMON_LEVEL[6]) #Level 7
print(BELDUM,CAN,LEARN,THE,TECHNIQUE,SAFEGUARD,AT,LEVEL,df.POKEMON_LEVEL[12]) #Level 13
print(BELDUM,CAN,LEARN,THE,TECHNIQUE,MAGNETBOMB,AT,LEVEL,df.POKEMON_LEVEL[16]) #Level 17 
print(BELDUM,CAN,LEARN,THE,TECHNIQUE,MAGNETRISE,AT,LEVEL,df.POKEMON_LEVEL[19]) #Level 20
print(BELDUM,CAN,LEARN,THE,TECHNIQUE,PSYCHICTERRAIN,AT,LEVEL,df.POKEMON_LEVEL[24]) #Level 25
print(BELDUM,CAN,LEARN,THE,TECHNIQUE,LOCKON,AT,LEVEL,df.POKEMON_LEVEL[34]) #Level 33
print(BELDUM,CAN,LEARN,THE,TECHNIQUE,REFRESH,AT,LEVEL,df.POKEMON_LEVEL[37]) #Level 38
print(BELDUM,CAN,LEARN,THE,TECHNIQUE,FOULPLAY,AT,LEVEL,df.POKEMON_LEVEL[44]) #Level 45
print(BELDUM,CAN,LEARN,THE,TECHNIQUE,SHADOWCLAW,AT,LEVEL,df.POKEMON_LEVEL[51]) #Level 50
print(BELDUM,CAN,LEARN,THE,TECHNIQUE,PSYCHOCUT,AT,LEVEL,df.POKEMON_LEVEL[54]) #Level 55
print(BELDUM,CAN,LEARN,THE,TECHNIQUE,METALCLAW,AT,LEVEL,df.POKEMON_LEVEL[61]) #Level 62
print(BELDUM,CAN,LEARN,THE,TECHNIQUE,IRONDEFENSE,AT,LEVEL,df.POKEMON_LEVEL[68]) #Level 69