from ListOfDirectoriesForAsunaAi import __FOLDER_PATH__
from ListOfDirectoriesForAsunaAi_2 import __PROGRAM_NAME__
from Pokemonarrayscript import *
from MasterScriptForte_Redone_2 import *
import pandas as pd
df = pd.read_excel (r'C:\ASUNAAI\EXTENSIONS\XLSX\TESTDATAFORPYTHONSCRIPT2.xlsx', sheet_name='POKEMON000DATA')
a = df['POKEMON_LEVEL']

print(RATICATE,CAN,LEARN,THE,TECHNIQUE,TACKLE,AT,LEVEL,df.POKEMON_LEVEL[9]) #Level 7
print(RATICATE,CAN,LEARN,THE,TECHNIQUE,QUICKATTACK,AT,LEVEL,df.POKEMON_LEVEL[15]) #Level 13
print(RATICATE,CAN,LEARN,THE,TECHNIQUE,TAILSLAP,AT,LEVEL,df.POKEMON_LEVEL[17]) #Level 17 
print(RATICATE,CAN,LEARN,THE,TECHNIQUE,DOUBLEHIT,AT,LEVEL,df.POKEMON_LEVEL[22]) #Level 20
print(RATICATE,CAN,LEARN,THE,TECHNIQUE,TAKEDOWN,AT,LEVEL,df.POKEMON_LEVEL[25]) #Level 25
print(RATICATE,CAN,LEARN,THE,TECHNIQUE,SCREECH,AT,LEVEL,df.POKEMON_LEVEL[37]) #Level 33
print(RATICATE,CAN,LEARN,THE,TECHNIQUE,DOUBLETEAM,AT,LEVEL,df.POKEMON_LEVEL[40]) #Level 38
print(RATICATE,CAN,LEARN,THE,TECHNIQUE,HYPERFANG,AT,LEVEL,df.POKEMON_LEVEL[47]) #Level 45
print(RATICATE,CAN,LEARN,THE,TECHNIQUE,SUPERFANG,AT,LEVEL,df.POKEMON_LEVEL[54]) #Level 50
print(RATICATE,CAN,LEARN,THE,TECHNIQUE,ENDEAVOR,AT,LEVEL,df.POKEMON_LEVEL[57]) #Level 55
print(RATICATE,CAN,LEARN,THE,TECHNIQUE,FLAMEWHEEL,AT,LEVEL,df.POKEMON_LEVEL[64]) #Level 62
print(RATICATE,CAN,LEARN,THE,TECHNIQUE,PSYCHICFANGS,AT,LEVEL,df.POKEMON_LEVEL[72]) #Level 69