from ListOfDirectoriesForAsunaAi import __FOLDER_PATH__
from ListOfDirectoriesForAsunaAi_2 import __PROGRAM_NAME__
from Pokemonarrayscript import *
from MasterScriptForte_Redone_2 import *
import pandas as pd
df = pd.read_excel (r'C:\ASUNAAI\EXTENSIONS\XLSX\TESTDATAFORPYTHONSCRIPT2.xlsx', sheet_name='POKEMON000DATA')
a = df['POKEMON_LEVEL']

print(DEERLING,CAN,LEARN,THE,TECHNIQUE,BULLETSEED,AT,LEVEL,df.POKEMON_LEVEL[6]) #Level 7
print(DEERLING,CAN,LEARN,THE,TECHNIQUE,DOUBLEKICK,AT,LEVEL,df.POKEMON_LEVEL[12]) #Level 13
print(DEERLING,CAN,LEARN,THE,TECHNIQUE,GRASSYTERRAIN,AT,LEVEL,df.POKEMON_LEVEL[16]) #Level 17 
print(DEERLING,CAN,LEARN,THE,TECHNIQUE,QUICKATTACK,AT,LEVEL,df.POKEMON_LEVEL[19]) #Level 20
print(DEERLING,CAN,LEARN,THE,TECHNIQUE,PROTECT,AT,LEVEL,df.POKEMON_LEVEL[24]) #Level 25
print(DEERLING,CAN,LEARN,THE,TECHNIQUE,LEAFBLADE,AT,LEVEL,df.POKEMON_LEVEL[34]) #Level 33
print(DEERLING,CAN,LEARN,THE,TECHNIQUE,MORNINGSUN,AT,LEVEL,df.POKEMON_LEVEL[37]) #Level 38
print(DEERLING,CAN,LEARN,THE,TECHNIQUE,DOUBLEEDGE,AT,LEVEL,df.POKEMON_LEVEL[44]) #Level 45
print(DEERLING,CAN,LEARN,THE,TECHNIQUE,SEEDBOMB,AT,LEVEL,df.POKEMON_LEVEL[51]) #Level 50
print(DEERLING,CAN,LEARN,THE,TECHNIQUE,LEECHSEED,AT,LEVEL,df.POKEMON_LEVEL[54]) #Level 55
print(DEERLING,CAN,LEARN,THE,TECHNIQUE,EXTREMESPEED,AT,LEVEL,df.POKEMON_LEVEL[61]) #Level 62
print(DEERLING,CAN,LEARN,THE,TECHNIQUE,EXTREMEEVOBOOST,AT,LEVEL,df.POKEMON_LEVEL[68]) #Level 69