from ListOfDirectoriesForAsunaAi import __FOLDER_PATH__
from ListOfDirectoriesForAsunaAi_2 import __PROGRAM_NAME__
from Pokemonarrayscript import *
from MasterScriptForte_Redone_2 import *
import pandas as pd
df = pd.read_excel (r'C:\ASUNAAI\EXTENSIONS\XLSX\TESTDATAFORPYTHONSCRIPT2.xlsx', sheet_name='POKEMON000DATA')
a = df['POKEMON_LEVEL']

print(SAWSBUCK,CAN,LEARN,THE,TECHNIQUE,BULLETSEED,AT,LEVEL,df.POKEMON_LEVEL[9]) #Level 10
print(SAWSBUCK,CAN,LEARN,THE,TECHNIQUE,DOUBLEKICK,AT,LEVEL,df.POKEMON_LEVEL[15]) #Level 16
print(SAWSBUCK,CAN,LEARN,THE,TECHNIQUE,GRASSYTERRAIN,AT,LEVEL,df.POKEMON_LEVEL[17]) #Level 18 
print(SAWSBUCK,CAN,LEARN,THE,TECHNIQUE,QUICKATTACK,AT,LEVEL,df.POKEMON_LEVEL[22]) #Level 23
print(SAWSBUCK,CAN,LEARN,THE,TECHNIQUE,PROTECT,AT,LEVEL,df.POKEMON_LEVEL[25]) #Level 26
print(SAWSBUCK,CAN,LEARN,THE,TECHNIQUE,LEAFBLADE,AT,LEVEL,df.POKEMON_LEVEL[37]) #Level 38
print(SAWSBUCK,CAN,LEARN,THE,TECHNIQUE,MORNINGSUN,AT,LEVEL,df.POKEMON_LEVEL[40]) #Level 41
print(SAWSBUCK,CAN,LEARN,THE,TECHNIQUE,DOUBLEEDGE,AT,LEVEL,df.POKEMON_LEVEL[47]) #Level 48
print(SAWSBUCK,CAN,LEARN,THE,TECHNIQUE,SEEDBOMB,AT,LEVEL,df.POKEMON_LEVEL[54]) #Level 59
print(SAWSBUCK,CAN,LEARN,THE,TECHNIQUE,LEECHSEED,AT,LEVEL,df.POKEMON_LEVEL[57]) #Level 58
print(SAWSBUCK,CAN,LEARN,THE,TECHNIQUE,EXTREMESPEED,AT,LEVEL,df.POKEMON_LEVEL[64]) #Level 65
print(SAWSBUCK,CAN,LEARN,THE,TECHNIQUE,EXTREMEEVOBOOST,AT,LEVEL,df.POKEMON_LEVEL[72]) #Level 72
