from ListOfDirectoriesForAsunaAi import __FOLDER_PATH__
from ListOfDirectoriesForAsunaAi_2 import __PROGRAM_NAME__
from Pokemonarrayscript import *
from MasterScriptForte_Redone_2 import *
import pandas as pd
df = pd.read_excel (r'C:\ASUNAAI\EXTENSIONS\XLSX\TESTDATAFORPYTHONSCRIPT2.xlsx', sheet_name='POKEMON000DATA')
a = df['POKEMON_LEVEL']
b = df['POKEMON_NUMBER']
c = df['POKEMON']
d = df['HP']
e = df['ATTACK']
f = df['DEFENSE']
g = df['SP. ATTACK']
h = df['SP. DEFENSE']
i = df['SPEED']
j = df['TOTAL']
k = df['AVERAGE']
print (APPROVE,BULBASAUR,POSSIBILITY,OBTAIN,TECHNIQUE,TACKLE,UPON,AT2,LEVEL,df.POKEMON_LEVEL[1])
print (APPROVE,BULBASAUR,POSSIBILITY,OBTAIN,TECHNIQUE,GROWL,UPON,AT2,LEVEL,df.POKEMON_LEVEL[1])
print (APPROVE,BULBASAUR,POSSIBILITY,OBTAIN,TECHNIQUE,VINEWHIP,UPON,AT2,LEVEL,df.POKEMON_LEVEL[3])
print (APPROVE,BULBASAUR,POSSIBILITY,OBTAIN,TECHNIQUE,GROWTH,UPON,AT2,LEVEL,df.POKEMON_LEVEL[6])
print (APPROVE,BULBASAUR,POSSIBILITY,OBTAIN,TECHNIQUE,LEECHSEED,UPON,AT2,LEVEL,df.POKEMON_LEVEL[9])
print (APPROVE,BULBASAUR,POSSIBILITY,OBTAIN,TECHNIQUE,RAZORLEAF,UPON,AT2,LEVEL,df.POKEMON_LEVEL[12])
print (APPROVE,BULBASAUR,POSSIBILITY,OBTAIN,TECHNIQUE,POISONPOWDER,UPON,AT2,LEVEL,df.POKEMON_LEVEL[15])
print (APPROVE,BULBASAUR,POSSIBILITY,OBTAIN,TECHNIQUE,SLEEPPOWDER,UPON,AT2,LEVEL,df.POKEMON_LEVEL[15])
print (APPROVE,BULBASAUR,POSSIBILITY,OBTAIN,TECHNIQUE,SEEDBOMB,UPON,AT2,LEVEL,df.POKEMON_LEVEL[18])
print (APPROVE,BULBASAUR,POSSIBILITY,OBTAIN,TECHNIQUE,TAKEDOWN,UPON,AT2,LEVEL,df.POKEMON_LEVEL[21])
print (APPROVE,BULBASAUR,POSSIBILITY,OBTAIN,TECHNIQUE,SWEETSCENT,UPON,AT2,LEVEL,df.POKEMON_LEVEL[24])
print (APPROVE,BULBASAUR,POSSIBILITY,OBTAIN,TECHNIQUE,SYNTHESIS,UPON,AT2,LEVEL,df.POKEMON_LEVEL[27])
print (APPROVE,BULBASAUR,POSSIBILITY,OBTAIN,TECHNIQUE,WORRYSEED,UPON,AT2,LEVEL,df.POKEMON_LEVEL[30])
print (APPROVE,BULBASAUR,POSSIBILITY,OBTAIN,TECHNIQUE,DOUBLEEDGE,UPON,AT2,LEVEL,df.POKEMON_LEVEL[33])
print (APPROVE,BULBASAUR,POSSIBILITY,OBTAIN,TECHNIQUE,SOLARBEAM,UPON,AT2,LEVEL,df.POKEMON_LEVEL[36])