def ROUTE211STARLYLEVELRANGE():
    LOWERLEVELRANGE = float(input('Enter A Level: '))
    HIGHERLEVELRANGE = float(input('Enter A Level: '))
    print('STARLY CAN BE FOUND WITH LEVELS BETWEEN LEVEL {0} TO LEVEL {1}'.format(LOWERLEVELRANGE, HIGHERLEVELRANGE))
ROUTE211STARLYLEVELRANGE()

def ROUTE211POOCHYENALEVELRANGE():
    LOWERLEVELRANGE = float(input('Enter A Level: '))
    HIGHERLEVELRANGE = float(input('Enter A Level: '))
    print('POOCHYENA CAN BE FOUND WITH LEVELS BETWEEN LEVEL {0} TO LEVEL {1}'.format(LOWERLEVELRANGE, HIGHERLEVELRANGE))
ROUTE211POOCHYENALEVELRANGE()

def ROUTE211WURMPLELEVELRANGE():
    LOWERLEVELRANGE = float(input('Enter A Level: '))
    HIGHERLEVELRANGE = float(input('Enter A Level: '))
    print('WURMPLE CAN BE FOUND WITH LEVELS BETWEEN LEVEL {0} TO LEVEL {1}'.format(LOWERLEVELRANGE, HIGHERLEVELRANGE))
ROUTE211WURMPLELEVELRANGE()

def ROUTE211PIKACHULEVELRANGE():
    LOWERLEVELRANGE = float(input('Enter A Level: '))
    HIGHERLEVELRANGE = float(input('Enter A Level: '))
    print('PIKACHU CAN BE FOUND WITH LEVELS BETWEEN LEVEL {0} TO LEVEL {1}'.format(LOWERLEVELRANGE, HIGHERLEVELRANGE))
ROUTE211PIKACHULEVELRANGE()

def ROUTE211ZORUALEVELRANGE():
    LOWERLEVELRANGE = float(input('Enter A Level: '))
    HIGHERLEVELRANGE = float(input('Enter A Level: '))
    print('ZORUA CAN BE FOUND WITH LEVELS BETWEEN LEVEL {0} TO LEVEL {1}'.format(LOWERLEVELRANGE, HIGHERLEVELRANGE))
ROUTE211ZORUALEVELRANGE()

#POOCHYENA CAN BE FOUND WITH LEVELS BETWEEN LEVEL {0} TO LEVEL {1}
